-- ============================================================
-- DDL - LocadoraCarros
-- Servidor: oracle.fiap.com.br:1521/ORCL
-- Schema:   rm562312
-- ============================================================

CREATE TABLE TB_CARROS (
    ID_CARRO     NUMBER          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    MODELO       VARCHAR2(100)   NOT NULL,
    MARCA        VARCHAR2(100)   NOT NULL,
    ANO          NUMBER(4)       NOT NULL,
    VALOR_DIARIA NUMBER(10,2)    NOT NULL
);

-- ============================================================
-- Dados de teste
-- ============================================================

INSERT INTO TB_CARROS (MODELO, MARCA, ANO, VALOR_DIARIA)
VALUES ('Civic', 'Honda', 2022, 150.00);

INSERT INTO TB_CARROS (MODELO, MARCA, ANO, VALOR_DIARIA)
VALUES ('Corolla', 'Toyota', 2023, 180.00);

INSERT INTO TB_CARROS (MODELO, MARCA, ANO, VALOR_DIARIA)
VALUES ('HB20', 'Hyundai', 2021, 90.00);

COMMIT;
